kind: pipeline
name: Network_CI_DC
type: docker

steps:
  - name: Render Configuration
    image: python:alpine3.17
    commands:
      - pip install -r requirements.txt
      - python ./send_config.py Templates/router_interfaces.j2 Configs/r1.yml