kind: pipeline
name: Network_CI_DC_With_Ansible
type: docker

steps:
  - name: Deploy with Ansible
    image: plugins/ansible:3
    settings:
      playbook: playbook
      inventory: inventory.ini
      syntax_check: true