interfaces:
  r1:
    - name: Ethernet0/2
      ip: 10.0.12.1/30
      description: "To R2"
      activate: False
    - name: Ethernet0/3
      ip: 10.0.13.1/30
      description: "To D3"
      activate: True
  r2:
    - name: Ethernet0/2
      ip: 10.99.12.1/30
      description: "To PE3"
      activate: True
    - name: Ethernet0/3
      ip: 10.99.13.1/30
      description: "To LAN"
      activate: True
  